name: Build Windows Binary

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: true

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
          version: 12.2.0

      - name: Set up env
        shell: bash
        run: |
          echo "CGO_ENABLED=1" >> $GITHUB_ENV

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: autozap.exe
          name: ${{ github.sha }}
